### ISSUE TITLE
PostgreSQL

### ISSUE THREAD

**Issue by renege** [andrey-helldar/migrate-db#10]
Hi @andrey-helldar 

it doesn’t work with postgresql 10? Correct? 13 and up only?
    ...

### Steps To Reproduce:

    ...

**Comment by andrey-helldar** [comment]
The package works with the standard Laravel database drivers.

According to the documentation, Laravel 8 supports the [PostgreSQL 9.5+](https://laravel.com/docs/8.x/queries#table-truncation-and-postgresql) database.

![image](https://user-images.githubusercontent.com/10347617/124671028-82d34080-debd-11eb-84d4-7f88c5623bc3.png)

What error are you getting?

**Comment by andrey-helldar** [comment]
I added tests for PgSQL 9, 10, 11, 12 and 13 versions to GitHub Actions and they succeed:

https://github.com/andrey-helldar/migrate-db/actions/runs/1005954605

![image](https://user-images.githubusercontent.com/10347617/124671883-d42fff80-debe-11eb-9633-48a370899918.png)

**Comment by andrey-helldar** [comment]
What versions are you using?

Migrate DB Version:
Laravel Version:
Database Name & Version: 
PHP Version:
