### ISSUE TITLE
Error: The "--schema-from" option does not accept a value.

### ISSUE THREAD

**Issue by hrslkvc** [andrey-helldar/migrate-db#8]
- Migrate DB Version: 1.0.1
- PHP Version: 7.4.16
- Laravel/Lumen Framework Version: 8.32.1

### Description:

Hey, I'm getting the error 'The "--schema-from" option does not accept a value' when trying to run the command provided in the readme. It happens for both the schema-from and schema-to options with any value. I took a look at the source code, and I think it happens because the command signature is missing '=' after the option names, which controls whether the option accepts values or not.

`protected $signature = 'db:migrate'
    . ' {--schema-from : Source connection name}'
    . ' {--schema-to : Target connection name}';`
    
I have added the equals signs after the option names locally and confirmed the command works fine after that. It looks like this

`protected $signature = 'db:migrate'
    . ' {--schema-from= : Source connection name}'
    . ' {--schema-to= : Target connection name}';`

Would you be interested in a pull request with this fix?

### Steps To Reproduce:

Install the package and run the command provided in the readme.

**Comment by andrey-helldar** [comment]
What error do you get?
The code has a [check](https://github.com/andrey-helldar/migrate-db/blob/main/src/Console/Migrate.php#L100-L113) for entering values.

**Comment by hrslkvc** [comment]
The error is: The "--schema-from" option does not accept a value

It doesnt even come to that check because/symfony/console/input/InputOption.php fails when it processes the options and returns an exception before the package even runs. 

I have tried supplying an empty value and then your check runs and handles null values properly so it works fine

**Comment by andrey-helldar** [comment]
That's it, I understand what the problem is. Now I'll fix it.

**Comment by andrey-helldar** [comment]
Released version [v1.0.2](https://github.com/andrey-helldar/migrate-db/releases/tag/v1.0.2).

Thank you!
